
import type { Report, AqiSensor, Citizen, Admin } from './types';
import { ReportCategory, ReportStatus, AdminRole } from './types';

export const mockCitizens: Citizen[] = [
    {
        id: 'user-001',
        janId: 'JAN-C-2024-0001',
        name: 'Amit Kumar',
        email: 'amit.kumar@example.com',
        phone: '9876543210',
        dateJoined: '2024-07-01T10:00:00Z',
        dob: '1990-05-15',
        address: 'House No. 123, Sector 17',
        city: 'Chandigarh',
        state: 'Chandigarh'
    },
    {
        id: 'user-002',
        janId: 'JAN-C-2024-0002',
        name: 'Priya Sharma',
        email: 'priya.sharma@example.com',
        phone: '9876543211',
        dateJoined: '2024-07-05T11:30:00Z',
        dob: '1992-08-22',
        address: 'House No. 456, Sector 22',
        city: 'Chandigarh',
        state: 'Chandigarh'
    },
    {
        id: 'user-003',
        janId: 'JAN-C-2024-0003',
        name: 'Sandeep Singh',
        email: 'sandeep.singh@example.com',
        phone: '9123456780',
        dateJoined: '2024-06-15T09:00:00Z',
        dob: '1988-11-01',
        address: 'House No. 789, Sector 35',
        city: 'Chandigarh',
        state: 'Chandigarh',
        bannedUntil: '2025-01-01T00:00:00Z'
    },
    {
        id: 'user-004',
        janId: 'JAN-C-2024-0004',
        name: 'Anjali Gupta',
        email: 'anjali.gupta@example.com',
        phone: '9988776655',
        dateJoined: '2024-07-10T15:20:00Z',
        dob: '1995-02-10',
        address: 'House No. 101, Sector 8',
        city: 'Chandigarh',
        state: 'Chandigarh'
    },
    {
        id: 'user-005',
        janId: 'JAN-C-2024-0005',
        name: 'Rahul Verma',
        email: 'rahul.verma@example.com',
        phone: '9001223344',
        dateJoined: '2024-05-20T18:00:00Z',
        dob: '1991-07-19',
        address: 'House No. 212, Sector 45',
        city: 'Chandigarh',
        state: 'Chandigarh',
        bannedUntil: 'lifetime'
    },
    {
        id: 'user-006',
        janId: 'JAN-C-2024-0006',
        name: 'Sneha Reddy',
        email: 'sneha.reddy@example.com',
        phone: '9555666777',
        dateJoined: '2024-07-12T12:00:00Z',
        dob: '1993-09-05',
        address: 'House No. 333, Sector 9',
        city: 'Chandigarh',
        state: 'Chandigarh'
    },
    {
        id: 'user-007',
        janId: 'JAN-C-2024-0007',
        name: 'Vikas Mehra',
        email: 'vikas.mehra@example.com',
        phone: '9444333222',
        dateJoined: '2024-07-18T10:30:00Z',
        dob: '1985-03-30',
        address: 'House No. 555, Sector 11',
        city: 'Chandigarh',
        state: 'Chandigarh'
    },
    {
        id: 'user-008',
        janId: 'JAN-C-2024-0008',
        name: 'Pooja Desai',
        email: 'pooja.desai@example.com',
        phone: '9666777888',
        dateJoined: '2024-07-20T11:00:00Z',
        dob: '1996-12-12',
        address: 'House No. 888, Sector 15',
        city: 'Chandigarh',
        state: 'Chandigarh'
    }
];

export const mockAdmins: Admin[] = [
    {
        id: 'admin-001',
        janId: 'JAN-K-2005-0001',
        email: 'super.admin@jancorp.com',
        name: 'Municipal Head',
        role: AdminRole.SuperAdmin,
        dateJoined: '2024-01-01T09:00:00Z',
    },
    {
        id: 'admin-002',
        janId: 'JAN-A-2024-0001',
        email: 'waste.admin@jancorp.com',
        name: 'Waste Dept Head',
        role: AdminRole.DepartmentAdmin,
        department: ReportCategory.Waste,
        dateJoined: '2024-02-15T09:00:00Z',
    },
    {
        id: 'admin-003',
        janId: 'JAN-A-2024-0002',
        email: 'pothole.admin@jancorp.com',
        name: 'Pothole Dept Head',
        role: AdminRole.DepartmentAdmin,
        department: ReportCategory.Pothole,
        dateJoined: '2024-02-15T09:00:00Z',
    },
    {
        id: 'admin-004',
        janId: 'JAN-A-2024-0003',
        email: 'streetlight.admin@jancorp.com',
        name: 'Streetlight Dept Head',
        role: AdminRole.DepartmentAdmin,
        department: ReportCategory.Streetlight,
        dateJoined: '2024-02-15T09:00:00Z',
    },
     {
        id: 'admin-005',
        janId: 'JAN-A-2024-0005',
        email: 'water.admin@jancorp.com',
        name: 'Water Dept Head',
        role: AdminRole.DepartmentAdmin,
        department: ReportCategory.Water,
        dateJoined: '2024-02-15T09:00:00Z',
    },
];

export const mockReports: Report[] = [
  {
    id: 'RPT-001',
    citizenId: 'user-001',
    category: ReportCategory.Waste,
    description: 'Large pile of garbage overflowing from the public bin near Sector 17 plaza. It has been there for 3 days.',
    latitude: 30.7352,
    longitude: 76.7826,
    imageUrl: 'https://picsum.photos/seed/waste1/400/300',
    reportDate: new Date('2024-07-18T08:00:00Z').toISOString(),
    status: ReportStatus.Pending,
    assignedAdminName: 'Unassigned',
    urgency: 'Medium',
    upvotes: 12,
    citizenIdsWhoUpvoted: ['user-002', 'user-003', 'user-004'],
  },
  {
    id: 'RPT-002',
    citizenId: 'user-002',
    category: ReportCategory.Pothole,
    description: 'Deep pothole on the Jan Marg road causing traffic issues. Very dangerous for two-wheelers.',
    latitude: 30.7415,
    longitude: 76.7824,
    imageUrl: 'https://picsum.photos/seed/pothole1/400/300',
    reportDate: new Date('2024-07-17T14:30:00Z').toISOString(),
    status: ReportStatus.InProgress,
    assignedAdminId: 'admin-003',
    assignedAdminName: 'Pothole Dept Head',
    urgency: 'High',
    upvotes: 25,
    citizenIdsWhoUpvoted: ['user-001', 'user-006', 'user-007', 'user-008'],
  },
  {
    id: 'RPT-003',
    citizenId: 'user-001',
    category: ReportCategory.Streetlight,
    description: 'The streetlight at the corner of the Rose Garden parking is not working. It is very dark at night.',
    latitude: 30.7423,
    longitude: 76.7942,
    imageUrl: '',
    reportDate: new Date('2024-07-15T20:00:00Z').toISOString(),
    status: ReportStatus.Resolved,
    assignedAdminId: 'admin-004',
    assignedAdminName: 'Streetlight Dept Head',
    urgency: 'Medium',
    resolution: {
      adminId: 'admin-004',
      adminName: 'Streetlight Dept Head',
      date: new Date('2024-07-16T12:00:00Z').toISOString(),
      summary: 'Replaced the faulty bulb and checked the wiring. The streetlight is now fully functional.',
      cost: 500,
      costBreakdown: 'New LED Bulb: Rs.350, Labor: Rs.150',
      afterImageUrl: 'https://picsum.photos/seed/light-fixed/400/300',
      citizenFeedback: 'Thank you for the quick action! The street feels much safer now.',
      citizenRating: 5,
      superAdminFeedback: 'Excellent turnaround time. Well done.',
      superAdminRating: 5,
      isApproved: true,
    },
    upvotes: 8,
    citizenIdsWhoUpvoted: [],
  },
  {
    id: 'RPT-004',
    citizenId: 'user-003',
    category: ReportCategory.Water,
    description: 'Severe water logging after the rain yesterday near Sukhna Lake path. The path is completely submerged.',
    latitude: 30.7422,
    longitude: 76.8188,
    imageUrl: 'https://picsum.photos/seed/water1/400/300',
    reportDate: new Date('2024-07-19T09:15:00Z').toISOString(),
    status: ReportStatus.Pending,
    assignedAdminName: 'Unassigned',
    urgency: 'High',
    upvotes: 30,
    citizenIdsWhoUpvoted: [],
  },
  {
    id: 'RPT-005',
    citizenId: 'user-004',
    category: ReportCategory.Other,
    description: 'Broken public bench in the Rock Garden. Needs immediate repair.',
    latitude: 30.7526,
    longitude: 76.8099,
    imageUrl: '',
    reportDate: new Date('2024-07-10T11:00:00Z').toISOString(),
    status: ReportStatus.PendingApproval,
    assignedAdminId: 'admin-002', // Assume waste handles it
    assignedAdminName: 'Waste Dept Head',
    urgency: 'Low',
     resolution: {
      adminId: 'admin-002',
      adminName: 'Waste Dept Head',
      date: new Date('2024-07-11T15:00:00Z').toISOString(),
      summary: 'The broken bench has been removed. A new one will be installed next week as per the park maintenance schedule.',
      cost: 1500,
      costBreakdown: 'Labor for removal: Rs.500, Disposal Fee: Rs.1000',
      afterImageUrl: 'https://picsum.photos/seed/bench-gone/400/300',
      citizenFeedback: 'Thanks for removing it, but when is the new one coming?',
      citizenRating: 3,
    },
    upvotes: 2,
    citizenIdsWhoUpvoted: [],
  },
  {
    id: 'RPT-006',
    citizenId: 'user-005',
    category: ReportCategory.Waste,
    description: 'Construction debris dumped on the side of the road in Sector 45.',
    latitude: 30.7063,
    longitude: 76.7686,
    imageUrl: 'https://picsum.photos/seed/waste2/400/300',
    reportDate: new Date('2024-07-20T10:00:00Z').toISOString(),
    status: ReportStatus.Rejected,
    assignedAdminName: 'Waste Dept Head',
    urgency: 'Low',
    upvotes: 0,
    citizenIdsWhoUpvoted: [],
  },
  {
    id: 'RPT-007',
    citizenId: 'user-006',
    category: ReportCategory.Pothole,
    description: 'Multiple small potholes on the road leading to Elante Mall.',
    latitude: 30.7056,
    longitude: 76.7997,
    imageUrl: 'https://picsum.photos/seed/pothole2/400/300',
    reportDate: new Date('2024-07-21T11:20:00Z').toISOString(),
    status: ReportStatus.PendingCitizenFeedback,
    assignedAdminId: 'admin-003',
    assignedAdminName: 'Pothole Dept Head',
    urgency: 'Medium',
    resolution: {
      adminId: 'admin-003',
      adminName: 'Pothole Dept Head',
      date: new Date('2024-07-22T10:00:00Z').toISOString(),
      summary: 'Applied temporary patchwork to all potholes. Awaiting budget for permanent resurfacing.',
      cost: 8000,
      costBreakdown: 'Tar: Rs.5000, Labor: Rs.3000',
      afterImageUrl: 'https://picsum.photos/seed/pothole-patched/400/300',
    },
    upvotes: 5,
    citizenIdsWhoUpvoted: [],
  },
  {
    id: 'RPT-008',
    citizenId: 'user-007',
    category: ReportCategory.Streetlight,
    description: 'Streetlight flickering continuously on the main road of Sector 11 market.',
    latitude: 30.7583,
    longitude: 76.7824,
    imageUrl: '',
    reportDate: new Date('2024-07-19T22:00:00Z').toISOString(),
    status: ReportStatus.InProgress,
    assignedAdminId: 'admin-004',
    assignedAdminName: 'Streetlight Dept Head',
    urgency: 'Medium',
    upvotes: 3,
    citizenIdsWhoUpvoted: [],
  },
   {
    id: 'RPT-009',
    citizenId: 'user-008',
    category: ReportCategory.Water,
    description: 'Leaking water pipeline near Sector 15 market.',
    latitude: 30.7483,
    longitude: 76.7808,
    imageUrl: 'https://picsum.photos/seed/water2/400/300',
    reportDate: new Date('2024-07-22T09:00:00Z').toISOString(),
    status: ReportStatus.Pending,
    assignedAdminName: 'Unassigned',
    urgency: 'High',
    upvotes: 18,
    citizenIdsWhoUpvoted: [],
  },
  {
    id: 'RPT-010',
    citizenId: 'user-001',
    category: ReportCategory.Pothole,
    description: 'The road surface has worn off completely near Sector 10.',
    latitude: 30.7461,
    longitude: 76.7813,
    imageUrl: 'https://picsum.photos/seed/pothole3/400/300',
    reportDate: new Date('2024-07-21T18:00:00Z').toISOString(),
    status: ReportStatus.InProgress,
    assignedAdminId: 'admin-003',
    assignedAdminName: 'Pothole Dept Head',
    urgency: 'High',
    upvotes: 7,
    citizenIdsWhoUpvoted: [],
  },
   {
    id: 'RPT-011',
    citizenId: 'user-002',
    category: ReportCategory.Waste,
    description: 'Garbage not collected for a week in our lane in Sector 40.',
    latitude: 30.7391,
    longitude: 76.7516,
    imageUrl: 'https://picsum.photos/seed/waste3/400/300',
    reportDate: new Date('2024-07-22T12:00:00Z').toISOString(),
    status: ReportStatus.Pending,
    assignedAdminName: 'Unassigned',
    urgency: 'Medium',
    upvotes: 9,
    citizenIdsWhoUpvoted: [],
  },
  {
    id: 'RPT-012',
    citizenId: 'user-003',
    category: ReportCategory.Other,
    description: 'Stray dogs have become a menace in the neighborhood park in Sector 21.',
    latitude: 30.7308,
    longitude: 76.7909,
    imageUrl: '',
    reportDate: new Date('2024-07-16T17:45:00Z').toISOString(),
    status: ReportStatus.Resolved,
    assignedAdminId: 'admin-002',
    assignedAdminName: 'Waste Dept Head',
    urgency: 'Low',
     resolution: {
      adminId: 'admin-002',
      adminName: 'Waste Dept Head',
      date: new Date('2024-07-18T12:00:00Z').toISOString(),
      summary: 'Coordinated with local animal welfare NGO. They have relocated the dogs to a shelter.',
      cost: 0,
      costBreakdown: 'Work done by NGO volunteers.',
      afterImageUrl: '',
      citizenFeedback: 'Great work, much appreciated!',
      citizenRating: 5,
      superAdminFeedback: 'Good use of community resources.',
      superAdminRating: 4,
      isApproved: true,
    },
    upvotes: 4,
    citizenIdsWhoUpvoted: [],
  },
  {
    id: 'RPT-013',
    citizenId: 'user-004',
    category: ReportCategory.Streetlight,
    description: 'Need a new streetlight installed in a dark alley in Sector 7.',
    latitude: 30.7360,
    longitude: 76.8021,
    imageUrl: '',
    reportDate: new Date('2024-07-14T19:30:00Z').toISOString(),
    status: ReportStatus.Rejected,
    assignedAdminId: 'admin-004',
    assignedAdminName: 'Streetlight Dept Head',
    urgency: 'Low',
    upvotes: 1,
    citizenIdsWhoUpvoted: [],
  },
  {
    id: 'RPT-014',
    citizenId: 'user-005',
    category: ReportCategory.Water,
    description: 'Main water supply pipe burst, flooding the street in Sector 34.',
    latitude: 30.7253,
    longitude: 76.7725,
    imageUrl: 'https://picsum.photos/seed/water3/400/300',
    reportDate: new Date('2024-07-22T06:00:00Z').toISOString(),
    status: ReportStatus.InProgress,
    assignedAdminId: 'admin-005',
    assignedAdminName: 'Water Dept Head',
    urgency: 'Critical',
    upvotes: 45,
    citizenIdsWhoUpvoted: [],
  },
   {
    id: 'RPT-015',
    citizenId: 'user-006',
    category: ReportCategory.Pothole,
    description: 'Road cave-in near Sector 17 market. Major traffic hazard.',
    latitude: 30.7335,
    longitude: 76.7821,
    imageUrl: 'https://picsum.photos/seed/pothole4/400/300',
    reportDate: new Date('2024-07-22T14:00:00Z').toISOString(),
    status: ReportStatus.Pending,
    assignedAdminName: 'Unassigned',
    urgency: 'Critical',
    upvotes: 50,
    citizenIdsWhoUpvoted: [],
  },
  ...[...Array(5)].map((_, i) => ({
    id: `RPT-FAKE-${i+1}`,
    citizenId: 'user-005',
    category: ReportCategory.Other,
    description: `This is false report #${i+1} to trigger the ban system.`,
    latitude: 30.7 + i * 0.01,
    longitude: 76.7 + i * 0.01,
    imageUrl: '',
    reportDate: new Date(`2024-07-01T10:00:${i < 10 ? '0' : ''}${i}Z`).toISOString(),
    status: ReportStatus.Rejected,
    assignedAdminId: 'admin-001',
    assignedAdminName: 'Super Admin',
    urgency: 'Low',
    upvotes: 0,
    citizenIdsWhoUpvoted: [],
  } as Report)),
];

export const mockAqiSensors: AqiSensor[] = [
  {
    id: 'AQI-01',
    location: { lat: 30.7333, lng: 76.7794 }, // Sector 17
    aqi: 158,
    name: 'Central Chandigarh Sensor',
  },
  {
    id: 'AQI-02',
    location: { lat: 30.7179, lng: 76.7448 }, // Sector 43
    aqi: 95,
    name: 'South Chandigarh Sensor',
  },
  {
    id: 'AQI-03',
    location: { lat: 30.7526, lng: 76.8099 }, // Rock Garden
    aqi: 210,
    name: 'North Chandigarh Sensor',
  },
  {
    id: 'AQI-04',
    location: { lat: 30.7410, lng: 76.7900 }, // Panjab University
    aqi: 180,
    name: 'West Chandigarh Sensor',
  },
  {
    id: 'AQI-05',
    location: { lat: 30.7056, lng: 76.7997 }, // Elante Mall
    aqi: 165,
    name: 'Industrial Area Sensor',
  },
  {
    id: 'AQI-06',
    location: { lat: 30.7422, lng: 76.8188 }, // Sukhna Lake
    aqi: 120,
    name: 'East Chandigarh Sensor',
  },
];

export const reportCategories = Object.values(ReportCategory);
