import type { Report, AqiSensor, Citizen, Admin } from './types';
import { ReportCategory, ReportStatus, AdminRole } from './types';

export const mockCitizens: Citizen[] = [
    {
        id: 'user-001',
        janId: 'JAN-C-2024-0001',
        name: 'Amit Kumar',
        email: 'amit.kumar@example.com',
        phone: '9876543210',
        dateJoined: '2024-07-01T10:00:00Z',
        dob: '1990-05-15',
        address: '123, MG Road, Saket',
        city: 'New Delhi',
        state: 'Delhi'
    },
    {
        id: 'user-002',
        janId: 'JAN-C-2024-0002',
        name: 'Priya Sharma',
        email: 'priya.sharma@example.com',
        phone: '9876543211',
        dateJoined: '2024-07-05T11:30:00Z',
        dob: '1992-08-22',
        address: '456, GK-1, Greater Kailash',
        city: 'New Delhi',
        state: 'Delhi'
    },
    {
        id: 'user-003',
        janId: 'JAN-C-2024-0003',
        name: 'Sandeep Singh',
        email: 'sandeep.singh@example.com',
        phone: '9123456780',
        dateJoined: '2024-06-15T09:00:00Z',
        dob: '1988-11-01',
        address: '789, Lajpat Nagar',
        city: 'New Delhi',
        state: 'Delhi'
    },
    {
        id: 'user-004',
        janId: 'JAN-C-2024-0004',
        name: 'Anjali Gupta',
        email: 'anjali.gupta@example.com',
        phone: '9988776655',
        dateJoined: '2024-07-10T15:20:00Z',
        dob: '1995-02-10',
        address: '101, Vasant Kunj',
        city: 'New Delhi',
        state: 'Delhi'
    },
    {
        id: 'user-005',
        janId: 'JAN-C-2024-0005',
        name: 'Rahul Verma',
        email: 'rahul.verma@example.com',
        phone: '9001223344',
        dateJoined: '2024-05-20T18:00:00Z',
        dob: '1991-07-19',
        address: '212, Rohini Sector 9',
        city: 'New Delhi',
        state: 'Delhi'
    },
    {
        id: 'user-006',
        janId: 'JAN-C-2024-0006',
        name: 'Sneha Reddy',
        email: 'sneha.reddy@example.com',
        phone: '9555666777',
        dateJoined: '2024-07-12T12:00:00Z',
        dob: '1993-09-05',
        address: '333, Hauz Khas Village',
        city: 'New Delhi',
        state: 'Delhi'
    },
    {
        id: 'user-007',
        janId: 'JAN-C-2024-0007',
        name: 'Vikas Mehra',
        email: 'vikas.mehra@example.com',
        phone: '9444333222',
        dateJoined: '2024-07-18T10:30:00Z',
        dob: '1985-03-30',
        address: '555, Karol Bagh',
        city: 'New Delhi',
        state: 'Delhi'
    },
    {
        id: 'user-008',
        janId: 'JAN-C-2024-0008',
        name: 'Pooja Desai',
        email: 'pooja.desai@example.com',
        phone: '9666777888',
        dateJoined: '2024-07-20T11:00:00Z',
        dob: '1996-12-12',
        address: '888, Connaught Place',
        city: 'New Delhi',
        state: 'Delhi'
    }
];

export const mockAdmins: Admin[] = [
    {
        id: 'admin-001',
        janId: 'JAN-K-2005-0001',
        email: 'super.admin@jancorp.com',
        name: 'Municipal Head',
        role: AdminRole.SuperAdmin,
        dateJoined: '2024-01-01T09:00:00Z',
    },
    {
        id: 'admin-002',
        janId: 'JAN-A-2024-0001',
        email: 'waste.admin@jancorp.com',
        name: 'Waste Dept Head',
        role: AdminRole.DepartmentAdmin,
        department: ReportCategory.Waste,
        dateJoined: '2024-02-15T09:00:00Z',
    },
    {
        id: 'admin-003',
        janId: 'JAN-A-2024-0002',
        email: 'pothole.admin@jancorp.com',
        name: 'Pothole Dept Head',
        role: AdminRole.DepartmentAdmin,
        department: ReportCategory.Pothole,
        dateJoined: '2024-02-15T09:00:00Z',
    },
    {
        id: 'admin-004',
        janId: 'JAN-A-2024-0003',
        email: 'streetlight.admin@jancorp.com',
        name: 'Streetlight Dept Head',
        role: AdminRole.DepartmentAdmin,
        department: ReportCategory.Streetlight,
        dateJoined: '2024-02-15T09:00:00Z',
    },
     {
        id: 'admin-005',
        janId: 'JAN-A-2024-0005',
        email: 'water.admin@jancorp.com',
        name: 'Water Dept Head',
        role: AdminRole.DepartmentAdmin,
        department: ReportCategory.Water,
        dateJoined: '2024-02-15T09:00:00Z',
    },
];

export const mockReports: Report[] = [
  {
    id: 'RPT-001',
    citizenId: 'user-001',
    category: ReportCategory.Waste,
    description: 'Large pile of garbage overflowing from the public bin near Saket metro station. It has been there for 3 days.',
    latitude: 28.5246,
    longitude: 77.2012,
    imageUrl: 'https://picsum.photos/seed/waste1/400/300',
    reportDate: new Date('2024-07-18T08:00:00Z').toISOString(),
    status: ReportStatus.Pending,
    assignedAdminName: 'Unassigned',
  },
  {
    id: 'RPT-002',
    citizenId: 'user-002',
    category: ReportCategory.Pothole,
    description: 'Deep pothole on the main road in GK-1 M-Block market causing traffic issues. Very dangerous for two-wheelers.',
    latitude: 28.5488,
    longitude: 77.2383,
    imageUrl: 'https://picsum.photos/seed/pothole1/400/300',
    reportDate: new Date('2024-07-17T14:30:00Z').toISOString(),
    status: ReportStatus.InProgress,
    assignedAdminId: 'admin-003',
    assignedAdminName: 'Pothole Dept Head',
  },
  {
    id: 'RPT-003',
    citizenId: 'user-001',
    category: ReportCategory.Streetlight,
    description: 'The streetlight at the corner of Nehru Place is not working. It is very dark at night and feels unsafe.',
    latitude: 28.5492,
    longitude: 77.2510,
    imageUrl: '',
    reportDate: new Date('2024-07-15T20:00:00Z').toISOString(),
    status: ReportStatus.Resolved,
    assignedAdminId: 'admin-004',
    assignedAdminName: 'Streetlight Dept Head',
    resolution: {
      adminId: 'admin-004',
      adminName: 'Streetlight Dept Head',
      date: new Date('2024-07-16T12:00:00Z').toISOString(),
      summary: 'Replaced the faulty bulb and checked the wiring. The streetlight is now fully functional.',
      cost: 500,
      costBreakdown: 'New LED Bulb: 350, Labor: 150',
      afterImageUrl: 'https://picsum.photos/seed/light-fixed/400/300',
      citizenFeedback: 'Thank you for the quick action! The street feels much safer now.',
      citizenRating: 5,
      superAdminFeedback: 'Excellent turnaround time. Well done.',
      superAdminRating: 5,
      isApproved: true,
    }
  },
  {
    id: 'RPT-004',
    citizenId: 'user-003',
    category: ReportCategory.Water,
    description: 'Severe water logging after the rain yesterday near ITO crossing. The road is completely submerged.',
    latitude: 28.6315,
    longitude: 77.2482,
    imageUrl: 'https://picsum.photos/seed/water1/400/300',
    reportDate: new Date('2024-07-19T09:15:00Z').toISOString(),
    status: ReportStatus.Pending,
    assignedAdminName: 'Unassigned',
  },
  {
    id: 'RPT-005',
    citizenId: 'user-004',
    category: ReportCategory.Other,
    description: 'Broken public bench in Lodhi Garden. Needs immediate repair.',
    latitude: 28.5932,
    longitude: 77.2225,
    imageUrl: '',
    reportDate: new Date('2024-07-10T11:00:00Z').toISOString(),
    status: ReportStatus.PendingApproval,
    assignedAdminId: 'admin-002', // Assume waste handles it
    assignedAdminName: 'Waste Dept Head',
     resolution: {
      adminId: 'admin-002',
      adminName: 'Waste Dept Head',
      date: new Date('2024-07-11T15:00:00Z').toISOString(),
      summary: 'The broken bench has been removed. A new one will be installed next week as per the park maintenance schedule.',
      cost: 1500,
      costBreakdown: 'Labor for removal: 500, Disposal Fee: 1000',
      afterImageUrl: 'https://picsum.photos/seed/bench-gone/400/300',
      citizenFeedback: 'Thanks for removing it, but when is the new one coming?',
      citizenRating: 3,
    }
  },
  {
    id: 'RPT-006',
    citizenId: 'user-005',
    category: ReportCategory.Waste,
    description: 'Construction debris dumped on the side of the road in Rohini Sector 9.',
    latitude: 28.7181,
    longitude: 77.1082,
    imageUrl: 'https://picsum.photos/seed/waste2/400/300',
    reportDate: new Date('2024-07-20T10:00:00Z').toISOString(),
    status: ReportStatus.Pending,
    assignedAdminName: 'Unassigned',
  },
  {
    id: 'RPT-007',
    citizenId: 'user-006',
    category: ReportCategory.Pothole,
    description: 'Multiple small potholes on the road leading to Hauz Khas Village.',
    latitude: 28.5535,
    longitude: 77.1943,
    imageUrl: 'https://picsum.photos/seed/pothole2/400/300',
    reportDate: new Date('2024-07-21T11:20:00Z').toISOString(),
    status: ReportStatus.PendingCitizenFeedback,
    assignedAdminId: 'admin-003',
    assignedAdminName: 'Pothole Dept Head',
    resolution: {
      adminId: 'admin-003',
      adminName: 'Pothole Dept Head',
      date: new Date('2024-07-22T10:00:00Z').toISOString(),
      summary: 'Applied temporary patchwork to all potholes. Awaiting budget for permanent resurfacing.',
      cost: 8000,
      costBreakdown: 'Tar: 5000, Labor: 3000',
      afterImageUrl: 'https://picsum.photos/seed/pothole-patched/400/300',
    }
  },
  {
    id: 'RPT-008',
    citizenId: 'user-007',
    category: ReportCategory.Streetlight,
    description: 'Streetlight flickering continuously on the main road of Karol Bagh market.',
    latitude: 28.6507,
    longitude: 77.1911,
    imageUrl: '',
    reportDate: new Date('2024-07-19T22:00:00Z').toISOString(),
    status: ReportStatus.InProgress,
    assignedAdminId: 'admin-004',
    assignedAdminName: 'Streetlight Dept Head',
  },
   {
    id: 'RPT-009',
    citizenId: 'user-008',
    category: ReportCategory.Water,
    description: 'Leaking water pipeline near Connaught Place, inner circle.',
    latitude: 28.6328,
    longitude: 77.2196,
    imageUrl: 'https://picsum.photos/seed/water2/400/300',
    reportDate: new Date('2024-07-22T09:00:00Z').toISOString(),
    status: ReportStatus.Pending,
    assignedAdminName: 'Unassigned',
  },
  {
    id: 'RPT-010',
    citizenId: 'user-001',
    category: ReportCategory.Pothole,
    description: 'The road surface has worn off completely near Chanakyapuri.',
    latitude: 28.5973,
    longitude: 77.1829,
    imageUrl: 'https://picsum.photos/seed/pothole3/400/300',
    reportDate: new Date('2024-07-21T18:00:00Z').toISOString(),
    status: ReportStatus.InProgress,
    assignedAdminId: 'admin-003',
    assignedAdminName: 'Pothole Dept Head',
  },
   {
    id: 'RPT-011',
    citizenId: 'user-002',
    category: ReportCategory.Waste,
    description: 'Garbage not collected for a week in our lane in Vasant Vihar.',
    latitude: 28.5630,
    longitude: 77.1636,
    imageUrl: 'https://picsum.photos/seed/waste3/400/300',
    reportDate: new Date('2024-07-22T12:00:00Z').toISOString(),
    status: ReportStatus.Pending,
    assignedAdminName: 'Unassigned',
  },
  {
    id: 'RPT-012',
    citizenId: 'user-003',
    category: ReportCategory.Other,
    description: 'Stray dogs have become a menace in the neighborhood park in Dwarka.',
    latitude: 28.6183,
    longitude: 77.0326,
    imageUrl: '',
    reportDate: new Date('2024-07-16T17:45:00Z').toISOString(),
    status: ReportStatus.Resolved,
    assignedAdminId: 'admin-002',
    assignedAdminName: 'Waste Dept Head',
     resolution: {
      adminId: 'admin-002',
      adminName: 'Waste Dept Head',
      date: new Date('2024-07-18T12:00:00Z').toISOString(),
      summary: 'Coordinated with local animal welfare NGO. They have relocated the dogs to a shelter.',
      cost: 0,
      costBreakdown: 'Work done by NGO volunteers.',
      afterImageUrl: '',
      citizenFeedback: 'Great work, much appreciated!',
      citizenRating: 5,
      superAdminFeedback: 'Good use of community resources.',
      superAdminRating: 4,
      isApproved: true,
    }
  },
  {
    id: 'RPT-013',
    citizenId: 'user-004',
    category: ReportCategory.Streetlight,
    description: 'Need a new streetlight installed in a dark alley in Malviya Nagar.',
    latitude: 28.5348,
    longitude: 77.2115,
    imageUrl: '',
    reportDate: new Date('2024-07-14T19:30:00Z').toISOString(),
    status: ReportStatus.Resolved,
    assignedAdminId: 'admin-004',
    assignedAdminName: 'Streetlight Dept Head',
  },
  {
    id: 'RPT-014',
    citizenId: 'user-005',
    category: ReportCategory.Water,
    description: 'Main water supply pipe burst, flooding the street in Patel Nagar.',
    latitude: 28.6468,
    longitude: 77.1720,
    imageUrl: 'https://picsum.photos/seed/water3/400/300',
    reportDate: new Date('2024-07-22T06:00:00Z').toISOString(),
    status: ReportStatus.InProgress,
    assignedAdminId: 'admin-005',
    assignedAdminName: 'Water Dept Head',
  },
   {
    id: 'RPT-015',
    citizenId: 'user-006',
    category: ReportCategory.Pothole,
    description: 'Road cave-in near India Gate circle. Major traffic hazard.',
    latitude: 28.6129,
    longitude: 77.2295,
    imageUrl: 'https://picsum.photos/seed/pothole4/400/300',
    reportDate: new Date('2024-07-22T14:00:00Z').toISOString(),
    status: ReportStatus.Pending,
    assignedAdminName: 'Unassigned',
  },
];

export const mockAqiSensors: AqiSensor[] = [
  {
    id: 'AQI-01',
    location: { lat: 28.6139, lng: 77.2090 }, // India Gate
    aqi: 158,
    name: 'Central Delhi Sensor',
  },
  {
    id: 'AQI-02',
    location: { lat: 28.5488, lng: 77.2383 }, // GK-1
    aqi: 95,
    name: 'South Delhi Sensor',
  },
  {
    id: 'AQI-03',
    location: { lat: 28.6562, lng: 77.2410 }, // Chandni Chowk
    aqi: 210,
    name: 'Old Delhi Sensor',
  },
  {
    id: 'AQI-04',
    location: { lat: 28.7041, lng: 77.1025 }, // Rohini
    aqi: 180,
    name: 'North West Delhi Sensor',
  },
  {
    id: 'AQI-05',
    location: { lat: 28.6183, lng: 77.0326 }, // Dwarka
    aqi: 165,
    name: 'West Delhi Sensor',
  },
  {
    id: 'AQI-06',
    location: { lat: 28.5276, lng: 77.2828 }, // Noida Border
    aqi: 230,
    name: 'East Delhi Sensor',
  },
];

export const reportCategories = Object.values(ReportCategory);
